import defaultTheme from 'tailwindcss/defaultTheme'

export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  theme: {
    extend: {
      colors: {
        'primary-dark': '#0f172a',
        'primary-light': '#f8fafc',
        'accent-light': '#eff6ff',
        'accent-blue': '#2563eb',
        'accent-blue-dark': '#1d4ed8',
        'accent-gray': '#e2e8f0',
        'page-bg': '#f5f2ec',
        'card-bg': '#ffffff',
        'text-primary': '#0f172a',
        'text-secondary': '#334155',
        'text-tertiary': '#475569',
        'border-gray': '#94a3b8',
        'button-primary': '#1f2937',
        'button-secondary': '#e2e8f0',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        '2xl': '48px',
        '3xl': '64px',
        'spacing-xs': '4px',
        'spacing-sm': '8px',
        'spacing-md': '16px',
        'spacing-lg': '24px',
        'spacing-xl': '32px',
        'spacing-2xl': '48px',
        'spacing-3xl': '64px',
      },
      fontSize: {
        'h1': ['44px', { lineHeight: '1.2', fontWeight: '700' }],
        'h1-mobile': ['28px', { lineHeight: '1.2', fontWeight: '700' }],
        'h2': ['32px', { lineHeight: '1.25', fontWeight: '700' }],
        'h2-mobile': ['22px', { lineHeight: '1.25', fontWeight: '700' }],
        'h3': ['24px', { lineHeight: '1.3', fontWeight: '700' }],
        'h3-mobile': ['20px', { lineHeight: '1.3', fontWeight: '700' }],
        'h4': ['20px', { lineHeight: '1.35', fontWeight: '600' }],
        'h5': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-mobile': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'small': ['14px', { lineHeight: '1.4', fontWeight: '400' }],
        'tiny': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      screens: {
        'xs': '320px',
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1440px',
      },
    },
    fontFamily: {
      sans: ['system-ui', '-apple-system', 'BlinkMacSystemFont', '"Segoe UI"', 'Roboto', 'sans-serif'],
    },
  },
  plugins: [],
}
